### ISSUE TITLE
Add CTA about inviting author to speak

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/blog#102]
```
Want to hear <name> to speak at your meetup?
-> link to madewithlove.be/conference-speaking page
```

above:

Share the :mwl:

**Comment by yannickdepauw** [comment]
![image](https://cloud.githubusercontent.com/assets/9960784/23470652/42129dc0-fea7-11e6-873a-c7ba926c6bf2.png)

![image](https://cloud.githubusercontent.com/assets/9960784/23470664/50a847b8-fea7-11e6-9515-c3741a6ad2eb.png)


![image](https://cloud.githubusercontent.com/assets/9960784/23470657/46feb38c-fea7-11e6-91bc-26855399b878.png)

**Comment by hannesvdvreken** [comment]
@Sambego Might need to refactor this first:

https://github.com/madewithlove/blog/blob/8514df7910564fc0737827981ad3af555d727b88/scripts/social.js#L40

https://github.com/madewithlove/blog/blob/8514df7910564fc0737827981ad3af555d727b88/_layouts/post.html#L13-L16

Then add the necessary static html (1 for a single author, 1 for multiple authors) and then I'll make it dynamic using the jekyll stuff. Unless you want to do that of course.
