### ISSUE TITLE
Fix the Heading of some blog posts

### ISSUE THREAD

**Issue by AchoArnold** [madewithlove/blog#112]
Some blog posts have some meta data-ish text at the beginning of the blog posts which I think should not be there? e.g

![screenshot 2018-09-20 12 50 44](https://user-images.githubusercontent.com/4196457/45816576-f76c6e80-bcd3-11e8-835a-05058f19fd0d.png)

**Comment by andreascreten** [comment]
Solved! Thanks for letting us know.
