### ISSUE TITLE
Content license change

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/blog#27]
Currently the site says:

> Content is published under MIT license, more info and the source material can be found on GitHub.

I don't think MIT is an appropriate license [for content]. Maybe we should switch to [Creative Commons BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) license instead?

**Comment by hannesvdvreken** [comment]
I discussed with some licensing experts, they seem to agree.

**Comment by eliedevlieger** [comment]
Fine for me.
