### ISSUE TITLE
Show comments

### ISSUE THREAD

**Issue by eliedevlieger** [madewithlove/blog#59]
I know this was already discussed, but I would still show the comments by default when opening a blogpost. Even if the page loads a bit slower. It's a bit strange and uninviting to have to click on 'show comments'.

**Comment by hannesvdvreken** [comment]
Or maybe, when a div at the bottom become visible (after scroll), it loads it. What do you think?

**Comment by eliedevlieger** [comment]
Is this what you meant @andreascreten? Fine for me in any case

**Comment by andreascreten** [comment]
Yes

**Comment by juarezpaf** [comment]
We can delay the Disqus loading for a few seconds after the page loads. I also don't like to click a button to be able to comment.
