### ISSUE TITLE
HTTP verb explanation issues in API blogpost

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/blog#62]
- `It's commonly used to create new instances of the endpoint.`  
  > `It's commonly used to add new resources to a collection`
- `it should return a 200 or 204 http code with an empty body, otherwise it should return a 201 with should contain a body (with the newly created resource in it) and a location header.`  
  > `it should return a `204 No Content` HTTP status code (success, empty response), or a `201 Created` response which should contain the created resource and optionally a location header where the new resource can be found.`

- `The main difference here is that PUT alters data, where POST adds data. The PUT is always executed on a resource like animals/wombats/1 if the wombat with id 1 doesn't exist, it's allowed to transform this in a POST (You don't have to).`  
  This is not correct, you can PUT to `/users/newusername` to try and create a user for this (hopefully) not yet used username. A POST request on `animals/wombats/1` is _not done_. So change this to:
   `The main difference here is that POST creation is done on the collection, PUT creation is done on a resource URI (like... give an example here). PUT can also be used to alter a resource. Executing the same PUT request multiple times should only create or alter the resource once: its action should be idempotent.`
- `A PATCH request uses instructions on how to handle the update.`  
  > `According to the RFC (link) a PATCH request should contain instructions on how to partially update a resource.`

Writing about REST is not easy as there are many different interpretations. Sorry I didn't fully check the meaning of your words before publishing :wink: but this is educating too.

**Comment by vanbrabantf** [comment]
Implemented, Thx.
