### ISSUE TITLE
Add disqus to allow comments on blog posts

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/blog#7]
https://disqus.com/websites/
There is no disqus -> slack notification hook, but you can use https://github.com/jonathanwiesel/slackus on heroku...

**Comment by hannesvdvreken** [comment]
Is this wanted? If not, we can close this. If this is wanted, I can add it, just need a company account.

**Comment by Anahkiasen** [comment]
I'd like that

**Comment by hannesvdvreken** [comment]
@andreascreten do we have a disqus account? https://disqus.com/madewithlove

**Comment by andreascreten** [comment]
I don't think that is us.
