### ISSUE TITLE
Type changed midway

### ISSUE THREAD

**Issue by kshiitiz** [madewithlove/blog#85]
In blog/_posts/2015-02-27-elasticsearch-aggregations.md , in the beginning the type has been given as 'sales' later its 'stock'. Make it uniform. Also change localghost to localhost, unless there is a pun intended.

**Comment by hannesvdvreken** [comment]
@tonysm can you extract what you did in #91 but only what is needed to resolve this inconsistency mentioned in this issue?

**Comment by tonysm** [comment]
Thanks, fixed in my PR with a revamped version of the Laravel and Elasticsearch integration article.
